export const languages={
    "English":{
        text1:"CROPDOC",
        text2:"Welcome",
        text3:"Disease",
        text4:"Identification",
        text5:"Crop",
        text6:"Recommendation",
        text7:"Agriculture",
        text8:"News",
        text9:"Activity",
        text10:"DashBoard",
        text11:"DISEASE IDENTIFICATION",
        text12:"Solution",
        text13:"Nitrogen Content of Soil",
        text14:"Phosphorus content of Soil",
        text15:"Potassium Content of Soil",
        text16:"pH value of Soil",
        text17:"Select Season",
        text18:"Summer",
        text19:"Winter",
        text20:"Monsoon",
        text21:"Autumn",
        text22:"Predict",
        text23:"Predicted Crop",
        text24:"AGRICULTURE NEWS",
        text25:"ACTIVITY DASHBOARD",
        text26:"Add",
        text27:"Create New Task",
        text28:"Title",
        text29:"Number of plantations",
        text30:"Plantation Date",
        text31:"Number of weeks to harvest",
        text32:"Close",
        text33:"Your Lists",
        text34:"Create New Entry",
        text35:"Description",
        text36:"PROFILE",
        text37:"Name",
        text38:"Email",
        text39:"Select Language",
        text40:"Enter your email",
        text41:"Password",
        text42:"Don't have an account?",
        text43:"Sign Up",
        text44:"Register",
        text45:"Enter your Username",
        text46:"Enter your Email",
        text47:"Password",
        text48:"Register",
        text49:"Already have an account?",
        text50:"Logout",
        text51:"CROP RECOMMENDATION",
        text52:"Nothing to display"
    },
    
    বাংলা:{
        text1:"ক্রপডক",
        text2: "স্বাগত",
        text3: "রোগ",
        text4:"পরিচয়",
        text5:"ফসলের",
        text6: "সুপারিশ",
        text7:"কৃষি",
        text8:"নিউজ",
        text9:"ক্রিয়াকলাপ",
        text10:"ড্যাশবোর্ড",
        text11: "রোগ সনাক্তকরণ",
        text12:"সমাধান",
        text13: "মাটির নাইট্রোজেন উপাদান",
        text14: "মাটির ফসফরাস উপাদান",
        text15: "মাটির পটাসিয়াম উপাদান",
        text16:"মাটির pH মান",
        text17: "ঋতু নির্বাচন করুন",
        text18:"গ্রীষ্ম",
        text19:"শীতকাল",
        text20:"বর্ষা",
        text21:"শরৎ",
        text22: "ভবিষ্যদ্বাণী করুন",
        text23: "অনুমানিত ফসল",
        text24:"কৃষি সংবাদ",
        text25:"অ্যাক্টিভিটি ড্যাশবোর্ড",
        text26:"যোগ করুন",
        text27: "নতুন টাস্ক তৈরি করুন",
        text28:"শিরোনাম",
        text29: "আবাদের সংখ্যা",
        text30: "বৃক্ষরোপণের তারিখ",
        text31: "ফসল কাটতে সপ্তাহের সংখ্যা",
        text32:"বন্ধ",
        text33:"আপনার তালিকা",
        text34: "নতুন এন্ট্রি তৈরি করুন",
        text35:"বর্ণনা",
        text36:"প্রোফাইল",
        text37: "নাম",
        text38:"ইমেল",
        text39: "ভাষা নির্বাচন করুন",
        text40: "আপনার ইমেইল লিখুন",
        text41:"পাসওয়ার্ড",
        text42: "একাউন্ট নেই?",
        text43:"সাইন আপ",
        text44:"নিবন্ধন করুন",
        text45: "আপনার ব্যবহারকারীর নাম লিখুন",
        text46: "আপনার ইমেইল লিখুন",
        text47:"পাসওয়ার্ড",
        text48:"নিবন্ধন করুন",
        text49:"ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
        text50:"লগআউট",
        text51:"ফসলের সুপারিশ",
        text52:"প্রদর্শনের কিছু নেই"
    },
    हिंदी:{
        text1:"क्रॉपडॉक",
        text2:"स्वागत है",
        text3:"बीमारी",
        text4:"पहचान",
        text5:"फसल",
        text6:"सिफारिश",
        text7:"कृषि",
        text8:"समाचार",
        text9:"गतिविधि",
        text10:"डैशबोर्ड",
        text11:"बीमारी की पहचान",
        text12:"समाधान",
        text13:"मिट्टी की नाइट्रोजन सामग्री",
        text14:"मिट्टी में फास्फोरस की मात्रा",
        text15:"मिट्टी की पोटेशियम सामग्री",
        text16:"मिट्टी का pH मान",
        text17:"सीज़न चुनें",
        text18:"ग्रीष्म",
        text19:"शीतकालीन",
        text20:"मानसून",
        text21:"शरद ऋतु",
        text22:"भविष्यवाणी करें",
        text23:"अनुमानित फसल",
        text24:"कृषि समाचार",
        text25:"गतिविधि डैशबोर्ड",
        text26:"जोड़ें",
        text27:"नया कार्य बनाएं",
        text28:"शीर्षक",
        text29:"वृक्षारोपण की संख्या",
        text30:"वृक्षारोपण तिथि",
        text31:"फसल काटने के लिए सप्ताहों की संख्या",
        text32:"बंद करें",
        text33:"आपकी सूचियाँ",
        text34:"नई प्रविष्टि बनाएं",
        text35:"विवरण",
        text36:"प्रोफ़ाइल",
        text37:"नाम",
        text38:"ईमेल",
        text39:"भाषा चुनें",
        text40:"अपना ईमेल दर्ज करें",
        text41:"पासवर्ड",
        text42:"क्या आपके पास कोई खाता नहीं है?",
        text43:"साइन अप करें",
        text44:"रजिस्टर करें",
        text45:"अपना उपयोगकर्ता नाम दर्ज करें",
        text46:"अपना ईमेल दर्ज करें",
        text47:"पासवर्ड",
        text48:"रजिस्टर करें",
        text49:"क्या आपके पास पहले से ही एक खाता है?",
        text50:"लॉगआउट",
        text51:"फसल अनुशंसा",
        text52:"कुछ भी प्रदर्शित नहीं करना"
    }
}

